# Generated by Django 5.1.2 on 2024-11-02 07:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('machine', models.CharField(max_length=255)),
                ('problem', models.TextField()),
                ('tel', models.CharField(max_length=12)),
            ],
        ),
    ]
